FROM python:3.11

WORKDIR /app
COPY requirements.txt /app/requirements.txt
# RUN pip install pipenv
# RUN pipenv install -r /app/requirements.txt
# RUN pipenv upgrade

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY  . /app/

CMD bash -c "while true; do sleep 1; done"

